In [1]:
import cv2

In [2]:
import numpy as np

In [37]:
img = np.random.rand()

In [38]:
img =np.random.randint(5, size=(4, 4))
img

array([[2, 1, 0, 4],
       [3, 2, 3, 0],
       [3, 1, 2, 0],
       [1, 2, 3, 0]])

In [16]:
img_new = [[1],[2],[2]]
for i in range(0,img.shape[0]):
    for j in range(0,img.shape[1]):
        img_new[i][j]=0
#         if(i==0 or i==img.shape[0] or j==0 or j==img.shape[1]):
#             img_new[i][j]=0
#         else:
#             img_new[i][j]=img[i-1][j-1]
    

IndexError: list assignment index out of range

In [39]:
w= img.shape[0]
h=img.shape[1]
img_new = [[0 for x in range(w+2)] for y in range(h+2)] 

In [40]:
img_new

[[0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0]]

In [41]:
for i in range(1,w+1):
    for j in range(1,h+1):
#         if(i==0 or i==w+1 or j==0 or j==h+1):
#             img_new[i][j]=0
#         else:
        img_new[i][j]=img[i-1][j-1]
img_new
    

[[0, 0, 0, 0, 0, 0],
 [0, 2, 1, 0, 4, 0],
 [0, 3, 2, 3, 0, 0],
 [0, 3, 1, 2, 0, 0],
 [0, 1, 2, 3, 0, 0],
 [0, 0, 0, 0, 0, 0]]

ValueError: setting an array element with a sequence.

In [82]:
a=np.asarray(res)
a.shape

(258, 258)

In [83]:
cv2.imshow("resimage",a)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [151]:
img = cv2.imread(r"C:\Users\aditya vikram\Desktop\project1\project1\data\proj1-task1.jpg",0)
sobel = [[1,0,-1],[2,0,-2],[1,0,-1]]
cv2.imshow("ts",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
sobel =np.asarray(sobel)
def convolve2d(img, kernel):
    """Convolves a given image and a given kernel.

    Steps:
        (1) flips the either the img or the kernel.
        (2) pads the img or the flipped img.
            this step handles pixels along the border of the img,
            and makes sure that the output img is of the same size as the input image.
        (3) applies the flipped kernel to the image or the kernel to the flipped image,
            using nested for loop.

    Args:
        img: nested list (int), image.
        kernel: nested list (int), kernel.

    Returns:
        img_conv: nested list (int), image.
    """
    # TODO: implement this function.
    k_flipped = [[0 for x in range(kernel.shape[0])] for y in range(kernel.shape[1])]
    for i in range(kernel.shape[0]):
        for j in range (kernel.shape[1]):
            k_flipped[i][j]=kernel[kernel.shape[0]-i-1][kernel.shape[1]-j-1]
    print(k_flipped)
    h= img.shape[0]
    w=img.shape[1]
    img_pad=[[0 for x in range(h+2)] for y in range(w+2)]
    print(np.shape(img_pad))
    for i in range(1,h+1):
        for j in range(1,w+1):
            img_pad[i][j]=img[i-1][j-1]
    k_ht = kernel.shape[0]//2
    k_wd = kernel.shape[1]//2
    #img_conv=[[0 for x in range(img_pad.shape[0])] for y in range(img_pad.shape[1])]
    img_conv = []
    img_conv_elem = []
    m=0
    n=0
    sm=0
    for i in range(0,len(img_pad)-2):
        for j in range(0,len(img_pad)-2):
            m=0
            for k in range(i,i+3):
                for l in range(j,j+3):
                    sm = sm + img_pad[k][l] * k_flipped[m][n]
                    n=n+1
                n = 0 
                m=m+1
            img_conv_elem.append(sm)
            sum = 0
        img_conv.append(img_conv_elem)
        img_conv_elem = []

    print(np.shape(img_conv))
    #raise NotImplementedError
    return img_conv

In [160]:
res=convolve2d(img,sobel)

[[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]]
(258, 258)
(256, 256)


In [179]:
res =np.asarray(res)
res


array([[ 111,  111,  111, ...,   51,   51,  -30],
       [ 118,  118,  118, ...,   38,   38,  -70],
       [  78,   78,   78, ...,    0,    0, -109],
       ...,
       [-107, -103,  -95, ...,    7,    7,  -62],
       [ -50,  -46,  -38, ...,   62,   62,   -6],
       [   3,    6,   12, ...,   87,   87,   36]])

In [157]:
cv2.imshow("ts",np.asarray(res))
cv2.waitKey(0)
cv2.destroyAllWindows()


In [117]:
test = np.random.randint(255,size=(6,6))

In [118]:
test

array([[ 75, 161, 140, 130,  49,  61],
       [  6, 143, 203,   7, 134, 108],
       [213, 213,  99, 169, 182, 129],
       [220, 251, 223,  81,   3, 167],
       [ 28, 178, 167,  14, 172, 232],
       [ 91, 133,  44, 207,  16, 118]])

In [122]:
t = convolve2d(test,sobel)

[[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]]


In [123]:
t

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, -75, -161, -140, 0, 0, 0],
 [0, 0, -6, -143, -203, 0, 0, 0],
 [0, 0, -213, -213, -99, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0]]

In [126]:
def elmwise_mul(a,b):
    c = []
    for i in range(0,len(a)):
        temp=[]
        for j in range(0,len(a[0])):
            temp.append(a[i][j] * b[i][j])
        c.append(temp)
    return c

# used to flatten multi dimensional array to single dimension to find sum, max, min etc.
def flatten_arr(arr):
    result = []
    for i in range(len(arr)):
        for j in range(len(arr[0])):
            result.append(arr[i][j])
    return result
def conv(img, kernel, kernel_size):        
    result = []
    # flips the kernel for convolution
    kernel = kernel[::-1][::-1]
    for i in range(img.shape[0]):
        if i <= img.shape[0] - kernel_size:
            row = []
            for j in range(img.shape[1]):
                if j <= img.shape[1] - kernel_size:
                    # element wise multiplication with kernel and calculates sum and appends to the result
                    img_arr = np.asarray(img[i:i+kernel_size, j:j+kernel_size])
                    temp = elmwise_mul(kernel, img_arr)
                    temp = sum(flatten_arr(temp))
                    row.append(temp)
            result.append(row)
    return result


In [132]:
a=np.asarray(conv(img,sobel,3))
a.shape


[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [ -4  -8 -12 ...   0   0   0]
 [ -4  -8 -12 ...   0   0   0]
 [ -4  -8 -12 ...   0   0   0]]


In [131]:
cv2.imshow("tr", a)
cv2.waitKey(0)

-1

In [140]:
print(a[20][80])

17


In [182]:
def norml(img, flag = False):
    max=0
    min =0
    elem = []
    nor = []
    n = len(img)
    for i in range(0,n):
        for j in range(0,n):
            if(img[i][j]>max):
                max = img[i][j]
            if(img[i][j]<min):
                min = img[i][j]
    diff = max - min
    
    for i in range(0,n):
        for j in range(0,n):
            # Multiplying by 255 here check
            if(flag == False):
                elem.append( ((img[i][j]-min)/diff) * 255 )
            elif(flag == True):
                elem.append( ((img[i][j]-min)/diff))
        nor.append(elem)
        elem = []
    #raise NotImplementedError
    return nor

In [183]:
n = norml(res)

256